<?php
/**
 * @file
 * Main simple_ldap module file.
 */

/**
 * Implements hook_menu().
 */
function simple_ldap_menu() {
  $items = array();

  $items['admin/config/people/simple_ldap'] = array(
    'title' => 'Simple LDAP Configuration',
    'description' => 'LDAP server, authentication parameters, roles, provisioning, etc.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('simple_ldap_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'simple_ldap.admin.inc',
  );

  $items['admin/config/people/simple_ldap/server'] = array(
    'title' => 'Server',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/**
 * Returns whether simple_ldap has been configured.
 */
function simple_ldap_configured() {
  $configured = TRUE;
  $config = config('simple_ldap.settings');

  // Check each of the required configuration items.
  $configured = $configured && $config->get('simple_ldap_host') !== NULL;
  $configured = $configured && $config->get('simple_ldap_port') !== NULL;

  return $configured;
}

/**
 * Implements hook_autoload_info().
 */
function simple_ldap_autoload_info() {
  return array(
    'SimpleLdap' => 'SimpleLdap.class.php',
    'SimpleLdapException' => 'SimpleLdapException.class.php',
    'SimpleLdapSchema' => 'SimpleLdapSchema.class.php',
    'SimpleLdapServer' => 'SimpleLdapServer.class.php',
    'SimpleLdapServerTestCase' => 'tests/SimpleLdapServerTestCase.class.php',
  );
}

/**
 * Implements hook_config_info().
 */
function simple_ldap_config_info() {
  $prefixes['simple_ldap.settings'] = array(
    'label' => t('Simple LDAP settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}
